### PR TITLE
upgrading hst version to 15

### PR DESCRIPTION
**Pull request by nileshdeepak-bloomreach**

### CODE REVIEW

**Comment by maxgda** [comment]
upgrade libraries in pom.xml:
apache commons to apache commons 3
log4j sl4j versions have security vulnerabilities, upgrade
jackrabbit version upgrade
brxm v15.1 is already out, use the newest

**Comment by maxgda** [comment]
delete travis ci from pom

 ```
 <ciManagement>
    <system>Travis CI</system>
    <url>https://travis-ci.org/bloomreach-forge/hst-content-version-utils</url>
  </ciManagement>
```

**Comment by jeroenhoffman** [comment]
I removed Travis and bumped  Jackrabbit version. 

It's in a mergeable state but we could extend the pom from hippo-cms7-project pom so we can inherit a lot of versioning and Maven plugin configuration.

**Comment by maxgda** [comment]
> I removed Travis and bumped Jackrabbit version.
> 
> It's in a mergeable state but we could extend the pom from hippo-cms7-project pom so we can inherit a lot of versioning and Maven plugin configuration.

Yes, I told @nileshdeepak-bloomreach to inherit from hippo-cms7-project like you advised him. Waiting for the change.

@nileshdeepak-bloomreach could you give us an update about this?

**Pull request merged**
